# Generated by Django 4.2.2 on 2023-06-21 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Currency',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='cur_value',
        ),
        migrations.AddField(
            model_name='item',
            name='currency_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.currency'),
        ),
    ]
